### PR TITLE
fix: expand advanced parameters accordion on validation errors

### LINKED ISSUE #740: Expand "Advanced Parameters" in SFT UI if there errors during submission
https://github.com/user-attachments/assets/53ddd5e0-8382-4eba-a0e0-f2cde6434bf7

If you try to submit and the errors are inside an accordion that is closed, we should expand the accordion.

### PR DESCRIPTION
**Pull request by ChetanXpro**
Fixes #740 

----

> [!IMPORTANT]
> Expands `AdvancedParametersAccordion` on validation errors and displays error messages for specific fields.
> 
>   - **Behavior**:
>     - Expands `AdvancedParametersAccordion` on validation errors for `validationSplitPercent`, `maxSamples`, or `threshold`.
>     - Uses `useEffect` and `useState` to manage accordion state based on `useFormState` errors.
>   - **UI**:
>     - Displays error messages below inputs for `validationSplitPercent` and `maxSamples` in `AdvancedParametersAccordion`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=tensorzero%2Ftensorzero&utm_source=github&utm_medium=referral)<sup> for c321886a2e6a6621d126bb0e2b9981ff97c4edd3. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: dashboard/app/routes/optimization/supervised-fine-tuning/AdvancedParametersAccordion.tsx [hunk 1]
```diff
@@ -18,8 +20,30 @@ export function AdvancedParametersAccordion({
...
   maxSamplesLimit,
 }: AdvancedParametersAccordionProps) {
+  const [isOpen, setIsOpen] = useState(false);
+
+  const { errors } = useFormState({
+    control,
+  });
+
+  const hasAdvancedErrors = Boolean(
+    errors.validationSplitPercent || errors.maxSamples || errors.threshold,
```
Comment (virajmehta) [inline dashboard/app/routes/optimization/supervised-fine-tuning/AdvancedParametersAccordion.tsx:30]: shouldn't threshold be handled in the MetricSelector component? it can't throw an error so nothing needs to be done but I think you should remove it from here just for hygiene

**Review by virajmehta — CHANGES_REQUESTED** [review]
one tiny change, otherwise LGTM

File: dashboard/app/routes/optimization/supervised-fine-tuning/AdvancedParametersAccordion.tsx (hunk 1 above)
Comment (ChetanXpro) [reply dashboard/app/routes/optimization/supervised-fine-tuning/AdvancedParametersAccordion.tsx]: My bad, yeah it does not make sense. I was trying different things and forgot to remove threshold check.

Comment (virajmehta) [reply dashboard/app/routes/optimization/supervised-fine-tuning/AdvancedParametersAccordion.tsx]: ok looks good. we're currently merging the move from `dashboard/` to `ui/` so I'll fix the conflict and we can merge right after!

Comment (ChetanXpro) [reply dashboard/app/routes/optimization/supervised-fine-tuning/AdvancedParametersAccordion.tsx]: Sounds good

**Review by virajmehta — APPROVED** [review]

**Comment by virajmehta** [comment]
@ChetanXpro thanks for the contribution!
