### PR TITLE
Validates there are credentials for models used by variants with positive weight

### LINKED ISSUE #224: Gateway should fail on startup if there are variants with weight that use API keys that haven't been provided
Should also consider how this interacts with API keys provided at request time

### PR DESCRIPTION
**Pull request by virajmehta**
Closes #224

### CODE REVIEW

File: gateway/src/inference/providers/openai.rs [hunk 1]
```diff
@@ -120,6 +120,10 @@ impl InferenceProvider for OpenAIProvider {
         };
         Ok((chunk, stream))
     }
+
+    fn has_credentials(&self) -> bool {
+        self.api_key.is_some()
+    }
```
Comment (GabrielBianconi) [inline gateway/src/inference/providers/openai.rs:126]: If you're using an unauthenticated OpenAI-compatible endpoint, this will break.

We should check ~ "API base is None or API key is Some"

**Review by GabrielBianconi — CHANGES_REQUESTED** [review]

**Review by GabrielBianconi — APPROVED** [review]

**Comment by GabrielBianconi** [comment]
@ellipsis-dev review [retroactively add rich PR description]
